// Generated by CoffeeScript 1.3.3
var Server, messages, pkg, program, srv, util;

program = require('commander');

util = require('util');

Server = require('./server.js');

pkg = require('../package.json');

messages = require('../assets/messages.json');

program.version(pkg.version).option('-p, --port <port>', 'telnet port', 23).option('-f, --fps <rate>', 'custom fps value', 10).parse(process.argv);

srv = module.exports = new Server(program.port, program.fps);

srv.server.on('listening', function() {
  return console.log(util.format(messages.listening, program.port, program.fps));
});

process.on('uncaughtException', function(e) {
  switch (e.code) {
    case 'EACCES':
      return console.log(messages.startErr);
    default:
      return console.log('Oops! Something went wrong!');
  }
});
