// Generated by CoffeeScript 1.3.3
var char, chars, draw, exps, frIdx, frame, frames, idx, lIdx, line, newLine, source, _i, _j, _k, _len, _len1, _len2;

source = require('../assets/frames');

chars = require('../assets/characters');

draw = chars.draw;

frames = [];

exps = {};

for (frIdx = _i = 0, _len = source.length; _i < _len; frIdx = ++_i) {
  frame = source[frIdx];
  for (lIdx = _j = 0, _len1 = frame.length; _j < _len1; lIdx = ++_j) {
    line = frame[lIdx];
    newLine = [];
    for (idx = _k = 0, _len2 = line.length; _k < _len2; idx = ++_k) {
      char = line[idx];
      if (idx === 0) {
        newLine.push(draw[char]);
        newLine.push(chars.point);
      } else if (char !== line[idx - 1]) {
        newLine.push(chars.end);
        newLine.push(draw[char]);
        newLine.push(chars.point);
      } else {
        newLine.push(chars.point);
      }
      if (idx === (line.length - 1)) {
        newLine.push(chars.end);
      }
    }
    frame[lIdx] = newLine.join('');
  }
  source[frIdx] = frame.join('\r\n');
}

console.log(JSON.stringify(source));
